### ISSUE TITLE
Music Enhancements - New Features - Timeline / Info

### ISSUE THREAD

**Issue by shikhir-arora** [shikhir-arora/NadekoBot#16]
/// I am using 🔜 to indicate how long as a visual reference. So 🔜 means it's higher in the todo  than 🔜 🔜 , etc. The ⏳ are things planned for the not-so-next-week or, like, super near time. 

/// AKA they're things that will come as time permits. More of ⏳ = I expect it to be longer.

----

I have been busy fixing the major bug; that is the hang that comes from any presence change or stagnation. Nadeko is the most versatile musicbot from sheer features. It also has a very specific way of pausing and unpausing, while maintaining large playlist support and persistence if wanted. Because of this, it has some unique challenges. Very few large musicbots will persist long. For example, FredBoat (a large MusicBot made in JDA with Lavaplayer) will persist for 10 minutes by default on the self-hosted one, and it uses lavaplayer which is extremely ahead of the curve. Nadeko still has the best features and so many, hence my desire to ensure it doesn't hang or stop working!  

🆕 **The bug, fortunately, has been 'fixed', and PR'ed, but I am working on the requested preferred changes and that can be seen in the PR I put on this fork. I expect that to be done no later than end of day March 30.**  https://github.com/Kwoth/NadekoBot/pull/1139 is the referenced pull request on the Nadeko Git.

> The project here will be pushed to NadekoBot/dev on GitHub pending Kwoth's approval once I am finished, which should, again be no later than March 30 or so.

> If you need a fix now, or if you prefer the way I fixed it now with `!!mv` command and a buffering command for BotOwners, then you can fork my `dev` branch (`shikhir-arora/NadekoBot` => dev is the main branch for my fork). I always update it daily with the latest updates from the NadekoBot/dev official branch.

> The changes to the PR referenced above is here: https://github.com/shikhir-arora/NadekoBot/pull/8

<h4> **Please feel free to chime in. I am always open to suggestions! ** </h4>

Nadeko is also the only bot of this size to really use Google API (YouTube Data API) + SoundCloud directly. It works quite well, but many user issues are probably caused by Google's change of terms all the time blocking their song or returning malformed (unrelated) URL's, as one user did show me earlier.

-----

<h3> Features and Upcoming </h3>

✔  - !!mv fix per https://github.com/Kwoth/NadekoBot/pull/1139 *I am going to mark this as "fixed" because it is on my end, just different preferences. To confirm, with the link referenced there are no issues with hangs, queues, and the worst case is having to issue a built in buffer command that will auto-refresh your queue and start it off right where it left off, in any voice channel. 

🔜  This will be marked and updated with a bit more info by March 30 when I'm done or earlier. Will be the "async" fix that Kwoth wanted, but with buffering built in without any users having to worry, so it should be super seamless. It is just an extension of what I fixed already, I am working on it now. More to come here.

---

*The following was also fixed today for those who utilize the repeatplaylist/currentsong options a lot:*

✔  - https://github.com/Kwoth/NadekoBot/pull/1154 - `RepeatPlaylist` + `RepeatCurrentSong` caused a loop that would stack due to the nature of the `ConcurrentQueue` system in place. Bug was fixed in PR referenced.
 
----

<h4> Here are the features I am going to start implementing *afterwords* (which should be **soon!**):</h4> 

🔜 🔜 (current bugfix then this is at the top)- Not an issue to do as I looked at the code quite a bit and it is not an issue. When the above is done with buffering fixes as that is by far the most troubling and affecting issue -- I will do this feature. It was requested here: https://github.com/Kwoth/NadekoBot/issues/1066 and I know @Kwoth is busy. He mentioned he liked it, and I do too - It is also not terribly hard to implement at all even with the YouTube and SC API's. Will do this as soon as I am done with this bugfix.

 > 🆕 Again, the PR I submitted on Kwoth/NadekoBot (the `dev` fork here) is **100%** fixed for all hangs that I could heavily measure -  but it is not "automatic" (it is 60% of the times, the rest you have to issue `!!buffer`but you **never** lose your persistent state, playlists, etc. This is my current build and I've ran it for a week consistently with no `.die` or other issues.

Please see this video which was taken before enhancements if you are still not sure what I mean :-) https://www.youtube.com/watch?v=1y9M_KTdwH4&feature=youtu.be%27

(watch it in HD with closed captioning to see the full effect!)

------

<h4> These are things that will come in the future. New Bugfixes or other cool, non-musicbot related things can then take priority </h4>

*I have looked into these things, hence my inclusion, so they are actual things I've given thought to. I do plan to spend time on this, as promised in one of my posts a long time ago. Sadly, Discord.NET didn't do what I thought at the time they would for some reason, and we have to go a different 'route.' to get the major thing here done. 

See below:

----

⏳ **Future stuff in the works include:** slowly and elegantly (if approved by Kwoth and team, but I think they are open to it for sure) - moving away from Google API/SC and to an **efficient** version of something like `youtube-dl` (a good C# implementation) => I am not am anti-Google or Official key user, but this solves two issues or just repetition for the support team I'd assume: 1) people coming in confused for lack of playing tracks that are rejected by Google or SoundCloud for regional, copyright, or whatever reason (uploader could say he didn't want it, and the API is official so it will reject). They also update it semi-frequently and change rules with API's for regional differences. So the goal is to allow things like searches at least (metadata extraction is a BIG feature in lavaplayer, which makes it so efficient. We want to fetch the data smoothly so that loading playlists isn't as slow as it is with the official API. From then on this can go to potential switching for actual playing, but that is down the pipeline. 

- ⏳ Switch to an efficient "non-API" player, as just mentioned above, will fill more when time comes. 

- ⏳ ⏳ Spotify Playlist output - OK, this comes up **a lot** and we always say no, which I agree. That is why it is so low on this list. But, FredBoat does have a way of doing it, and I know it is possible. It is also slow - and that is coming from a lavaplayer - based bot  (you must queue the playlist from the API, then use another way of getting the parsed URL's from YouTube, SoundCloud, etc).

----

<h4> and finally...</h4>

- ⏳ ⏳ ⏳ - Eventually, the **real** "end means" is using something like lavaplayer, or at least direct encodings for the bindings. This was actually what I first posted about when I got Nadeko, and was my main thing I was talking about. It is at the bottom because there is so much and I need to do more research, but there are several promising things. We want something which gives closer or direct access to libopus (Not libsodium). This is much faster. YouTube for example is mostly encoded in containers that are native to libopus and hence lavaplayer takes advantage of this by using low-level direct C-headers and basically not waste resources. Why reencode with ffmpeg (which is lousy!) when you don't need to? Also improve the metadata extraction ways since we would be moving off of Google API likely by this point as mentioned.

Here are some things I looked at re: the above: 
---- 

> https://github.com/lostromb/concentus.oggfile   [Concentus Extention for ogg]

> https://github.com/lostromb/concentus [Concentus - the best option IMO, will likely be it unless something comes up]

> https://github.com/jasl8r/P-Opus [P-Opus is good, faster slightly but not nearly as developed or maintained, so don't think it's worth it, but I put it up here anyways]

----

**MISC: **

> 🔉  I am looking into something that no other MusicBot has, namely lyrics output. It is a hard feature to do stylistically, but this is something that is interesting. It is not a priority at all, at least right now.

----

That's "all" for now. Will update accordingly. Back to work on those bugs :-)!

**Comment by ghost** [comment]
What the hell

**Comment by shikhir-arora** [comment]
@Kwoth Sorry you have a grudge against me for some reason, but when someone posts a giant thing of features they want to do and a timeline, including fixing the issue that **still causes most people using the bot to hang** because the move command fix was apparently not good, and yet I am just adding open source features and putting them in a post.

> What the hell

What are *you* even worried about? This is like me saying "Hey @Kwoth, these are some of my thoughts. This is what I'm planning to do." What did you think, I'm going to package them up and sell them to the highest bidder?! No, these are purely enhancements to make your project, one that I financially contribute to, better. As said in the above post:

> **(if approved by Kwoth and team.....)**

Which should be obvious, since you are the sole authority of what gets pushed to the NadekoBot/dev.

I am just helping here: be it fixing bugs or talking about adding features, yet your passive-aggressiveness towards a *financial supporter* of your bot is extremely disconcerting and a bit 'disrespectful' for business, IMO. Please let me know when I have bothered you or what I have done to always get sarcastic responses and nothing truly serious. Are you telling me the ~$100 or so I've donated and all of the things I've pushed annoy you to this degree? 

When someone tells you "Hey, I want to add some new features, of course they'll be pushed and commented on and changed per request of @Kwoth and team, and they only make Nadeko better" you shouldn't say **What the hell** -- it comes off pretty bad.  🤔

Why do you think I am fixing the issue the way you asked? I only speak the truth in this post btw. The fix I did **does** work, whether you think it's good or not, it works 100%. However, I am making it so that it toggles on `SocketVoiceState` like you asked, and will be done by Mar 30. AKA no move command and I wrote that above dude..

**Comment by shikhir-arora** [comment]
[!img](http://i.imgur.com/cjmhs2i.png)
